export const AIRPORT = {
  icao: 'KVBT',
  name: 'Thaden Field',
  city: 'Bentonville, AR',
  elevation_ft: 1304,
  lat: 36.3444,
  lon: -94.2211,
  runways: [
    { id: '18', heading_deg: 180, length_ft: 6006 },
    { id: '36', heading_deg: 360, length_ft: 6006 },
  ],
};

const C172S_VSPEEDS = {
  Va_table: [
    { weight_lb: 2550, kias: 105 },
    { weight_lb: 2200, kias: 98 },
    { weight_lb: 1900, kias: 90 },
  ],
  Vx: { kias: 62, label: 'Best angle climb' },
  Vy: { kias: 74, label: 'Best rate climb' },
  Vfe: { kias: 85, label: 'Max flap extension (full flaps)' },
  Vno: { kias: 129, label: 'Max structural cruise' },
  Vne: { kias: 163, label: 'Never exceed' },
  Vso: { kias: 40, label: 'Stall, landing config' },
  Vs1: { kias: 48, label: 'Stall, clean' },
};

export const FLEET = [
  {
    tail: 'N65965',
    type: 'C152',
    rules: 'VFR',
    hourly_rate: 135,
    equipment: '110 HP, Garmin Aera 500 GPS, ADS-B Out',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/96826e69237615d4eae7877788cc3c433a3649e3',
  },
  {
    tail: 'N137AL',
    type: 'C172N',
    rules: 'IFR',
    hourly_rate: 170,
    equipment: '180 HP, Garmin GNS 430W, STEC 30 Autopilot, Vortex Generators, ADS-B Out',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/358f0c2857182c6ff833fe59200b581cfc756450',
  },
  {
    tail: 'N733VR',
    type: 'C172N',
    rules: 'IFR',
    hourly_rate: 170,
    equipment: '180 HP, Garmin GNS 430W, ADS-B Out',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/45f187452f41a698901430bfe2c72d0df0cd99a2',
  },
  {
    tail: 'N172WN',
    type: 'C172N',
    rules: 'IFR',
    hourly_rate: 175,
    equipment: '180 HP, Garmin G5 PFD and HSI, Garmin GTN 650, Trio Pro Autopilot, ADS-B Out',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/dfc198a94930fe3c4ba898292f7216cbb5f82674',
  },
  {
    tail: 'N53068',
    type: 'Cessna 172S',
    rules: 'IFR',
    hourly_rate: 175,
    equipment: '180 HP, Garmin G5 PFD and HSI, Garmin GTN 650, BK KAP 140 Autopilot, ADS-B Out',
    primary: true,
    vspeeds: C172S_VSPEEDS,
    fuel_type: '100LL',
    fuel_burn_gph: 8.5,
    image_url: 'https://photos.flightaware.com/photos/retriever/e3e353e514deb71e3f4d44e4d1135d26754da83f',
  },
  {
    tail: 'N851SP',
    type: 'Cessna 172S',
    rules: 'IFR',
    hourly_rate: 175,
    equipment: '180 HP, BendixKing KLN 94 GPS, BK KMD 550 Multifunction Display, BK KAP 140 Autopilot, ADS-B Out',
    primary: false,
    vspeeds: C172S_VSPEEDS,
    fuel_type: '100LL',
    fuel_burn_gph: 8.5,
    image_url: 'https://photos.flightaware.com/photos/retriever/10379edaf136a637cd1caf54e3ecfcaa7bc547d6',
  },
  {
    tail: 'N840MC',
    type: 'Cessna 172S',
    rules: 'IFR',
    hourly_rate: 195,
    equipment: '180 HP, Garmin G1000 Avionics, BK KAP 140 Autopilot, ADS-B Out',
    primary: false,
    vspeeds: C172S_VSPEEDS,
    fuel_type: '100LL',
    fuel_burn_gph: 8.5,
    image_url: 'https://photos.flightaware.com/photos/retriever/df36e5a1e9b903fae3d17d00eb32f374972a9d86',
  },
  {
    tail: 'N758LM',
    type: 'R172K Hawk XP',
    rules: 'IFR',
    hourly_rate: 197,
    equipment: 'Isham 210 HP conversion, High Performance, TAA Autopilot, ADS-B Out',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/3e5300edbf428079bef06b3da0b1668b75ac0479',
  },
  {
    tail: 'N83552',
    type: 'PA18',
    rules: 'VFR',
    hourly_rate: 190,
    equipment: '180 HP, Garmin GNC 250XL, 26 inch tundra tires',
    primary: false,
    vspeeds: null,
    fuel_type: '100LL',
    fuel_burn_gph: null,
    image_url: 'https://photos.flightaware.com/photos/retriever/bce672c0fa205a0029d6b20b676678ed623bebbd',
  },
  {
    tail: 'Simulator',
    type: 'Redbird Simulator',
    rules: 'IFR',
    hourly_rate: 60,
    equipment: 'C172 analog GNS 530/430, C172 G1000, C182 analog GNS 530/430, Cirrus SR22 Perspective with CAPS handle',
    primary: false,
    vspeeds: null,
    fuel_type: null,
    fuel_burn_gph: null,
    image_url: null,
  },
];

export const PRIMARY_AIRCRAFT = FLEET.find((aircraft) => aircraft.primary) || FLEET[0];

export const DEFAULT_PERSONAL_MINIMUMS = {
  ceiling_ft: 3000,
  visibility_sm: 5,
  crosswind_kt: 10,
  wind_kt: 15,
  caution_margin_pct: 20,
};

export const PART_61_REQUIREMENTS = {
  total_hours: 40,
  dual_hours: 20,
  solo_hours: 10,
  solo_xc_hours: 5,
  solo_xc_long_nm: 150,
  night_hours: 3,
  night_xc_nm: 100,
  night_takeoffs_landings: 10,
  instrument_hours: 3,
  cross_country_dual: 3,
  three_takeoffs_landings_solo: 3,
};

export const MANEUVER_LIST = [
  'preflight_inspection',
  'normal_takeoff',
  'crosswind_takeoff',
  'normal_landing',
  'crosswind_landing',
  'short_field_takeoff',
  'short_field_landing',
  'soft_field_takeoff',
  'soft_field_landing',
  'go_around',
  'forward_slip',
  'slow_flight',
  'power_off_stall',
  'power_on_stall',
  'steep_turns',
  'turns_around_point',
  's_turns',
  'rectangular_course',
  'emergency_descent',
  'simulated_engine_failure',
  'unusual_attitudes_recovery',
  'hood_work_basic_instruments',
];

export const GROUND_SCHOOL_TOPICS = [
  'regulations',
  'weather_theory',
  'weather_services',
  'navigation',
  'airspace',
  'performance_wb',
  'aerodynamics',
  'aircraft_systems',
  'airport_ops',
  'radio_comms',
  'cross_country_planning',
  'physiology_aeromedical',
  'night_ops_theory',
  'emergency_procedures',
  'charts_publications',
  'flight_computers',
  'sectional_reading',
  'checkride_prep',
];

export function labelize(value) {
  return value.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
}
